services:
  - type: web
    name: recipeshare-server
    env: node
    rootDir: recipeshare-server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: JWT_SECRET
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: CORS_ORIGIN
        value: https://REPLACE_WITH_CLIENT.onrender.com

  - type: static_site
    name: recipeshare-client
    rootDir: recipeshare-client
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://REPLACE_WITH_SERVER.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
